### ISSUE TITLE
Hovering over any UI in a Youtube Video at fullscreen makes your FPS 10 with Hardware Acceleration off

### ISSUE THREAD

**Issue by ghost** [LawOff/YouTubeFluent#2]
this is caused by the CSS but I do not know how to fix it and I am surprised nobody has reported this yet

**Comment by RikisuT** [comment]
Unable to recreate this error

**Comment by RikisuT** [comment]
> this is caused by the CSS but I do not know how to fix it and I am surprised nobody has reported this yet

Unable to recreate this. Please provide browser details and specs

**Comment by ghost** [comment]
My browser is Chrome Beta and the important specs are:
CPU: AMD Ryzen 7 3700X 8-Core Processor
16GB of memory
Graphics card: NVIDIA GeForce RTX 3070

**Comment by RikisuT** [comment]
Hmm your specs are way above mine, so it should work. Might be cause of the beta version.
Cant think of anything else. Could you check if the code is updated to the newest version?

**Comment by ghost** [comment]
i tried using normal chrome and using the latest version yet I still get the lag, I will try Edge now and the text below will be after testing Edge:

turns out it was chrome entirely cause this issue and I will now become an Edge user :/

so anyone else reading this having the same issue, try Microsoft Edge.

**Comment by ghost** [comment]
turns out we both were wrong, the culprit was not the code nor the browser, the culprit was Hardware Acceleration, if it's off you get that insane lag, and I had it off for a reason but I guess it'll be on from now on, so ignore my previous statement.
