### ISSUE TITLE
2022 youtube new ui create issue withe theme

### ISSUE THREAD

**Issue by SiriosDev** [LawOff/YouTubeFluent#4]
at a glance the semi-transparencies disappear, but surely there must be more that doesn't jump out at you

**Comment by LawOff** [comment]
Hi, when I got the new interface, I had to put back the css and js.
Everything works as well as before.

**Comment by LawOff** [comment]
> at a glance the semi-transparencies disappear, but surely there must be more that doesn't jump out at you

Hi, when I got the new interface, I had to put back the css and js.
Everything works as well as before.

**Comment by LawOff** [comment]
I will see if there is some optimization to do.
